  
version: '2'

volumes:
  conf:
  data:
services:
  telegraf:
    image: telegraf@sha256:c49de7078369915b8db3410721714bc1b2f3f86b279b560aefb6adf8d2915413
    container_name: telegraf
    restart: always
    network_mode: "host"
    cap_add:
      - SYS_ADMIN
    labels:
      io.balena.features.balena: '1'
    volumes: 
      - 'conf:/data/conf'
    command: --config http://localhost:9099
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
    network_mode: "host"
  autowire:
    build: ./autowire
    restart: always
    network_mode: "host"
    labels:
      io.balena.features.balena: '1'
    ports:
      - 9099:9099
